/**
 * AI inference observability types for @flarelog/sdk.
 *
 * These types describe the structured payload FlareLog captures for every AI
 * inference call (chat completion, embedding, tool call, streaming response).
 * They are designed to map cleanly to OpenTelemetry span attributes so the
 * existing FlareLog/OTLP transports can ship them without any new
 * transport-side code.
 *
 * All attribute names follow the OpenTelemetry GenAI semantic conventions
 * (https://opentelemetry.io/docs/specs/semconv/gen-ai/) where possible, so
 * downstream backends (Grafana, Honeycomb, Datadog) render them correctly
 * out of the box.
 */

/**
 * A supported AI provider. Used both for routing (which response parser to
 * use) and as a span attribute (`gen_ai.provider.name`) for grouping in the
 * dashboard.
 *
 * Widened to `string` so that auto-detected providers from the opencode.ai
 * catalog (e.g. "openrouter", "groq", "deepseek") are supported without
 * requiring type-level maintenance as the catalog grows.
 */
export type AIProvider = string;

/**
 * Token usage breakdown. All fields are optional because not every provider
 * returns every field — e.g. Anthropic exposes `cache_read_input_tokens`
 * but OpenAI exposes `prompt_tokens_details.cached_tokens`.
 *
 * All counts are in tokens (not characters or bytes).
 */
export interface AITokenUsage {
  /** Tokens in the prompt that were processed fresh (not cached). */
  input?: number;
  /** Tokens generated by the model. */
  output?: number;
  /** Tokens pulled from a prompt cache (Anthropic, OpenAI cached inputs). */
  cachedInput?: number;
  /**
   * Reasoning tokens — OpenAI o1/o3 series, DeepSeek R1, etc.
   * Billed differently from regular output tokens.
   */
  reasoning?: number;
  /**
   * Tokens in the prompt that were marked as cacheable but not actually
   * served from cache (paid cache-write rate). Anthropic only.
   */
  cacheCreationInput?: number;
}

/**
 * Information about a single tool/function call the model made.
 * Captured for agent observability — lets you see which tools are hot,
 * which fail, and which models hallucinate tool names.
 */
export interface AIToolCall {
  /** Tool or function name (e.g. "get_weather", "search_web"). */
  name: string;
  /** Tool call ID assigned by the provider (for multi-turn correlation). */
  id?: string;
  /** Argument length in characters. We don't capture args by default (privacy). */
  argumentLength?: number;
  /** Argument length in tokens, if cheap to compute (heuristic: chars/4). */
  argumentTokens?: number;
}

/**
 * Latency breakdown for a single AI call. All values are in milliseconds.
 *
 * For streaming responses, `ttfb` is the time until the first SSE chunk
 * arrives (often the most important metric — long TTFB = slow model
 * cold-start or long prompt processing). `total` is wall-clock from request
 * sent to last byte received.
 */
export interface AILatency {
  /** Time to first byte (first SSE chunk for streams, full response for non-streams). */
  ttfb?: number;
  /** Total request duration. */
  total?: number;
  /** Number of SSE chunks received (streams only). */
  streamChunks?: number;
  /** Tokens/second for the output (output tokens / generation time). */
  tokensPerSecond?: number;
}

/**
 * The full structured record for a single AI inference call.
 *
 * This is what gets attached to the OTel span as attributes (with the
 * `gen_ai.*` and `flarelog.ai.*` prefixes) and also emitted as a log entry
 * for full-text search.
 */
export interface AICallRecord {
  /** Which provider handled the call. */
  provider: AIProvider;
  /** Model name as returned by the provider (e.g. "gpt-4o-2024-08-06"). */
  model: string;
  /** Operation type — chat, embedding, etc. */
  operation: AIOperation;
  /** Token usage breakdown. */
  tokens: AITokenUsage;
  /** Latency breakdown in milliseconds. */
  latency: AILatency;
  /** Estimated cost in USD (per-call, before any rounding). */
  costUsd?: number;
  /** HTTP response status code (undefined for binding-based calls like Workers AI). */
  status?: number;
  /** Provider-assigned request ID (for support tickets / correlation). */
  requestId?: string;
  /** Tool calls the model made (if any). */
  toolCalls?: AIToolCall[];
  /** Error type if the call failed (e.g. "rate_limit", "timeout", "context_length_exceeded"). */
  errorType?: string;
  /** Error message if the call failed. */
  errorMessage?: string;
  /** Number of retries that occurred (when using `wrap()` with retry). */
  retries?: number;
  /** Whether the response was streamed (SSE) or returned whole. */
  streamed?: boolean;
  /**
   * Optional user-provided tags (route, feature flag, customer ID, etc.).
   * These get attached as `flarelog.ai.tag.*` attributes for filtering.
   */
  tags?: Record<string, string>;
}

export type AIOperation =
  | "chat"
  | "completion"
  | "embedding"
  | "image"
  | "audio"
  | "moderation"
  | "rerank"
  | "tool"
  | "unknown";

/**
 * Configuration for the AI observability module.
 */
export interface AIInstrumentationConfig {
  /**
   * Whether to auto-patch global `fetch()` to intercept AI calls.
   * Default: `true`. Set to `false` if you only want explicit `wrap()`.
   */
  autoFetch?: boolean;

  /**
   * Whether to inject the W3C traceparent header on outgoing AI calls.
   * Default: `true`. Lets you correlate AI spans with their parent request
   * span across service boundaries.
   */
  propagateTrace?: boolean;

  /**
   * Whether to capture truncated prompt/completion samples.
   * Default: `false` (privacy-preserving). When enabled, captures the first
   * `maxPromptSampleChars` of the prompt and completion as span attributes.
   */
  captureSamples?: boolean;

  /** Max characters of prompt/completion to capture when `captureSamples` is on. Default: 500. */
  maxPromptSampleChars?: number;

  /**
   * Custom price table overrides. Merged with the built-in table.
   * Key is the model name (exact match, case-insensitive).
   * Value is USD per 1M tokens for each token category.
   */
  priceOverrides?: Record<string, PriceEntry>;

  /**
   * Multiplier applied to all computed costs. Useful for baked-in margin
   * or for tracking internal transfer cost vs customer-facing price.
   * Default: 1.0.
   */
  costMultiplier?: number;

  /**
   * Sample rate for AI spans (0.0 to 1.0). Independent of the logger's
   * global `sampleRate` so you can capture 100% of AI calls while sampling
   * other logs. Default: 1.0.
   */
  sampleRate?: number;

  /**
   * Filter function — return false to skip instrumentation for a request.
   * Useful for excluding internal/healthcheck calls.
   */
  shouldInstrument?: (url: string, method: string) => boolean;

  /**
   * List of additional hostname patterns to recognize as AI providers.
   * Each entry can be a string (substring match) or RegExp.
   * Useful for OpenAI-compatible gateways (e.g. Together, Groq, Anyscale).
   */
  extraProviderHosts?: Array<{ pattern: string | RegExp; provider: AIProvider }>;
}

/**
 * A single price entry in the cost table.
 * All values are USD per 1,000,000 tokens.
 */
export interface PriceEntry {
  /** USD per 1M input tokens. */
  input: number;
  /** USD per 1M output tokens. */
  output: number;
  /** USD per 1M cached input tokens (often 50% of input). */
  cachedInput?: number;
  /** USD per 1M reasoning tokens (o1/o3 series). */
  reasoning?: number;
  /** USD per 1M cache-write tokens (Anthropic). */
  cacheCreationInput?: number;
  /** Max input context window in tokens. */
  contextWindow?: number;
  /** Max output tokens the model can generate. */
  maxOutput?: number;
  /** Whether the model has a reasoning/thinking mode. */
  hasReasoning?: boolean;
  /** Whether the model supports tool/function calling. */
  hasToolCall?: boolean;
  /** Whether the model accepts attachments/images. */
  hasAttachment?: boolean;
  /** Supported input modalities, e.g. ["text", "image", "pdf"]. */
  inputModalities?: string[];
  /** Output modalities, e.g. ["text"]. */
  outputModalities?: string[];
}

/**
 * Result returned by a provider's response parser. The fetch interceptor
 * calls each provider's `match()` to decide ownership, then `parse()` to
 * extract structured data.
 */
export interface ProviderMatcher {
  /** Provider name. */
  name: AIProvider;
  /** Returns true if this URL+method looks like one of this provider's endpoints. */
  match: (url: string, method: string) => boolean;
  /**
   * Extract the model name from the request body (so we can look up the
   * price entry before the response arrives).
   */
  extractModel?: (requestBody: unknown) => string | undefined;
  /**
   * Extract the operation type from the URL path.
   * e.g. `/v1/chat/completions` → "chat", `/v1/embeddings` → "embedding".
   */
  extractOperation: (url: string) => AIOperation;
  /**
   * Parse a non-streaming JSON response body and extract token usage,
   * tool calls, and request ID.
   */
  parseResponse: (body: unknown) => {
    tokens?: AITokenUsage;
    toolCalls?: AIToolCall[];
    requestId?: string;
    model?: string;
  };
  /**
   * Parse a single SSE chunk from a streaming response. Should return
   * any usage delta seen in this chunk (often only the final chunk has
   * usage). Return `undefined` for chunks with no usage info.
   */
  parseStreamChunk?: (chunk: string) => {
    tokens?: AITokenUsage;
    toolCalls?: AIToolCall[];
    done?: boolean;
  } | undefined;
  /**
   * Parse an error response body to extract a structured error type
   * (e.g. "rate_limit_exceeded", "context_length_exceeded").
   *
   * Return `undefined` if the body doesn't match a known error shape.
   */
  parseError?: (status: number, body: unknown) => { type?: string; message?: string } | undefined;
}
